# Generated by Django 4.1.6 on 2023-02-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stuid", models.IntegerField()),
                ("stuname", models.CharField(max_length=255)),
                ("stuemail", models.EmailField(max_length=254)),
                ("stupass", models.CharField(max_length=100)),
            ],
        ),
    ]
