# Generated by Django 4.1.6 on 2023-03-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bolog',
            new_name='Blog',
        ),
    ]
