# Generated by Django 4.1.6 on 2023-02-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("stuid", models.IntegerField(primary_key=True, serialize=False)),
                ("stuname", models.CharField(max_length=70)),
                ("stuemail", models.EmailField(max_length=80)),
                ("stupass", models.CharField(max_length=70)),
            ],
        ),
    ]
